/* UI translations only. Member names, notes and expense descriptions are never translated. */
(() => {
  const en={
    '后台自动检查更新，不会刷新整个页面。也可点击“同步”。':'Updates happen in the background without reloading the page. You can also sync manually.',
    '所选周期全员总消费':'Selected period spending','我在此周期的消费':'My spending in this period','新密码':'New password','初始密码':'Initial password','重设密码（选填）':'New password (optional)',
    '密码不能为空，两次输入必须相同。':'Enter a password and make sure both entries match.','密码不能为空。':'Password cannot be empty.','密码不符合 Supabase 项目的规则，请检查后台密码设置。':'The password does not meet your Supabase project rules. Check the Auth password settings.',
    '彻底删除周期':'Delete period permanently','永久删除':'Delete permanently','取消':'Cancel',
    '将删除 {count} 笔消费，合计 {total}。':'Delete {count} expenses totalling {total}.',
    '此周期、全部消费和已删除记录的历史都会永久删除，无法恢复。':'This period, all expenses and previously deleted records will be permanently erased. This cannot be undone.',
    '输入完整周期名称确认':'Type the full period name to confirm','请输入完全相同的周期名称。':'Enter the exact period name.',
    '周期和全部消费已永久删除':'Period and all expenses permanently deleted','周期名称不一致，删除未执行。':'The period name does not match. Nothing was deleted.',
    '周期消费有更新，删除未执行。请关闭确认框，重新点击删除以核对最新金额。':'Expenses changed. Nothing was deleted. Close this dialog and reopen it to review the latest total.',
    '当前周期全员总消费':'Current period spending','我当前的消费':'My current spending','目前没有进行中的周期':'No active period right now','历史消费可在明细页查看':'View past spending on the Expenses page','所选周期总额':'Selected period total','我的消费':'My spending','消费笔数':'Number of expenses',
    '本期只展示自己的明细；所选周期总额仍包含所有成员。':'Only your own details are shown. The selected period total still includes everyone.',
    '改为普通会员':'Make member','设为管理员':'Make admin','角色已更新':'Role updated',
    '将此会员设为管理员？对方将可以管理会员、重设会员密码、管理周期和修改消费。':'Make this member an admin? They can manage members, reset member passwords, manage periods and edit expenses.',
    '将此管理员改为普通会员？对方会失去管理员权限，系统会保留至少一位管理员。':'Make this admin a regular member? They will lose admin access. At least one admin must remain.',
    '至少需要保留一位管理员，不能取消最后一位管理员。':'At least one admin must remain. The last admin cannot be demoted.',
    '请先恢复该会员，再设为管理员。':'Restore this member before making them an admin.',
    '无效的账号角色。':'Invalid account role.',
    '删除空周期':'Delete empty period',
    '确定删除这个空周期？删除后无法恢复；包含消费历史的周期不会被删除。':'Delete this empty period permanently? Periods with any expense history will be kept.',
    '空周期已删除':'Empty period deleted',
    '这个周期有消费历史，不能删除。可关闭周期保留账目。':'This period has expense history and cannot be deleted. Close it to preserve the records.',
    '昵称或头像无效，请检查后重试。':'Invalid name or photo. Please check and retry.','找不到该会员，请重新同步。':'Member not found. Please sync again.',
    '罗家记':'罗家记','一起花 · 一起记':'Little moments, together','账本概览':'Home','消费明细':'Expenses','团队成员':'Members','我们的家人':'Our family','概览':'Home','明细':'Expenses','成员':'Members','我的':'Me','记一笔':'Add','记一笔消费':'Add expense',
    '一起记，好好过':'A little note, a better day','。':'.','每一笔小日常，都值得好好记录。':'A home for every little everyday expense.','欢迎回到罗家记':'Welcome to Luo Family Ledger','登录你的账号，和大家一起记下今天。':'Sign in and record today, together.','使用管理员分配的账号登录。':'Sign in with the account your administrator created.','邮箱':'Email','密码':'Password','你的账号邮箱':'Your email address','登录账本':'Sign in','同步':'Sync','修改密码':'Change password','退出登录':'Sign out','新密码（至少 12 位）':'New password (12+ characters)','再次输入新密码':'Confirm new password','保存新密码':'Save password','首次使用？查看开通说明':'First time? Setup guide',
    '我们的共用账本':'OUR SHARED LEDGER','暂无记账周期':'No period yet','选择记账周期':'Select a period','管理员 · 开启新的记账周期':'Admin · Start a new period','周期名称':'Period name','例如：十月上半月共同消费':'e.g. October family expenses','开始日期':'Start date','结束日期（包含当天）':'End date (inclusive)','一星期':'1 week','两星期':'2 weeks','30 天':'30 days','成员可见范围':'Member visibility','全员总额和全部消费明细':'Team total and all expenses','全员总额和自己的明细':'Team total and own expenses','成员补记规则':'Backdating','只能记录当天':'Today only','允许补记周期内已过去的日期':'Allow past dates within the period','创建记账周期':'Create period','周期到结束日期的 23:59 后自动锁定。统一使用马来西亚时间（UTC+8）。':'Periods lock after 23:59 on the end date. All dates use Malaysia time (UTC+8).',
    '本期全员总消费':'Total family spending','一起生活的每一笔，都在这里。':'Every little moment, in one place.','等你记下第一笔':'Ready for your first entry','团队共享':'Shared ledger','我本期的消费':'My spending','每一笔，心中有数':'A clearer view of your everyday','一起记账的伙伴':'Contributors','记账规则':'Period rules','提前结束本期':'Close period early','管理员':'Admin','普通会员':'Member','进行中':'Active','未开始':'Upcoming','已到期':'Ended','已关闭':'Closed','等待开启':'Waiting to start','等待管理员开启周期':'Waiting for an admin to start a period','一起记下第一笔':'Let’s make our first entry','历史周期和总消费会保留。':'Past periods and totals are preserved.',
    '记录今天的消费':'Record an expense','消费金额':'Amount','消费内容':'Description','例如：午餐、咖啡、采购':'e.g. Lunch, coffee, groceries','日期':'Date','时间':'Time','消费分类':'Category','分类':'Category','餐饮':'Food','交通':'Transport','购物':'Shopping','居家':'Home','娱乐':'Leisure','健康':'Health','学习':'Learning','其他':'Other','添加备注':'Add a note','选填':'Optional','消费备注':'Expense note','补充消费说明':'Add a little detail','＋ 保存到共用账本':'Save expense','取消编辑':'Cancel edit','登录后记入团队的共用账本。':'Sign in to save to the shared ledger.','一起记账的人':'Our family','本期累计':'This period','筛选':'Filters','导出':'Export','下载 CSV':'Download CSV','下载本期 JSON':'Download JSON','整个周期':'All dates','今天':'Today','自选时间':'Date range','开始时间':'From','结束时间':'To','找一笔消费…':'Find an expense…','搜索消费':'Search expenses','全部成员':'All members','全部分类':'All categories','清除筛选':'Clear filters','编辑记录':'Edit','删除记录':'Delete','还没有符合条件的消费':'No matching expenses','周期内记下今天的第一笔，或调整筛选条件。':'Add your first expense or adjust the filters.','日常有账，生活有数。':'A little clarity, every day.','我':'Me','我的记录':'My expenses','保存修改':'Save changes',
    '查看本期消费，认识每一位一起记账的家人。':'Meet the people who share your everyday.','搜索成员昵称':'Search members','＋ 新增会员':'＋ Add member','更换头像':'Change photo','移除头像':'Remove photo','我的昵称':'My display name','保存个人资料':'Save profile','按日期、分类和成员查看每一笔':'Explore by date, category and member','查看成员、本期消费与会员管理':'People, spending and member management','新增会员':'Add member','管理会员':'Manage member','昵称':'Display name','登录邮箱':'Login email','初始密码（至少 12 位）':'Initial password (12+ characters)','重设密码（选填，至少 12 位）':'New password (optional, 12+ characters)','保存':'Save','关闭':'Close','已移除':'Removed','本期明细仅本人可见':'Only this member can see their details','共 {n} 笔消费':'{n} expenses','管理':'Manage','移除会员':'Remove','恢复会员':'Restore','没有找到成员':'No members found','请选择 10 MB 以内的 JPG、PNG 或 WebP 图片。':'Choose a JPG, PNG or WebP image up to 10 MB.','头像已预览，点击保存个人资料后同步。':'Preview ready. Save your profile to sync the photo.','图片读取失败，请换一张图片。':'Could not read this image. Please try another.','个人资料已保存':'Profile saved','创建后即可使用邮箱和初始密码登录。请私下交给本人。':'They can sign in with this email and password. Share the credentials privately.','可修改昵称或设置新密码。历史消费会继续保留。':'Update the name or set a new password. Past expenses are preserved.','移除后，该会员不能再使用账本，历史消费会保留。确定移除？':'Remove this member’s access? Their past expenses will be preserved.','恢复后，该会员可以再次登录使用账本。确定恢复？':'Restore this member’s access to the ledger?','正在保存…':'Saving…','会员资料已保存':'Member saved',
    '云端尚未开通':'Cloud not configured','请登录云端账本':'Please sign in','正在读取云端账本…':'Loading ledger…','正在读取团队账本…':'Loading shared ledger…','正在同步…':'Syncing…','● 团队账本已同步':'● Up to date','● 云端已保存':'● Saved to cloud','正在保存到云端…':'Saving to cloud…','同步失败 · 请重试':'Sync failed · Try again','保存未确认 · 请重试':'Save unconfirmed · Retry','正在登录…':'Signing in…','云端连接失败':'Connection failed','使用管理员分配的邮箱和密码登录。':'Use the email and password your admin provided.','使用管理员分配的邮箱和密码登录。没有账号或忘记密码，请联系管理员。':'Use your assigned email and password. Contact your admin if you need help.','全员共享周期总消费。页面每 20 秒检查更新，也可点击“同步”。':'Shared totals refresh every 20 seconds. You can also sync manually.','消费记入全员共用账本。保存成功后，其他成员同步即可看到。':'Saved expenses appear for other members when they sync.',
    '等待管理员开启记账周期。':'Waiting for an admin to create a period.','该周期尚未开始，开始后即可记账。':'This period has not started. Come back on the start date.','本周期已结束，记录保留供所有成员查看。':'This period is read-only. Past records remain available.','当前记录已不可修改，请取消编辑查看最新账本。':'This entry can no longer be edited. Cancel to view the latest ledger.','开始时间不能晚于结束时间。':'The start must be before the end.','本期只展示自己的明细；上方“本期全员总消费”仍包含所有成员。':'Only your details are visible. The family total still includes everyone.','本周期尚未开始或已结束，不能记账。':'This period is not open for entries.','请填写有效的消费金额、内容、日期和时间。':'Please enter a valid amount, description, date and time.','会员只能记录今天的消费。':'Members can only record today’s expenses.','日期必须在周期内，且不能晚于今天。':'Choose a date within the period, no later than today.','已保存到团队账本':'Expense saved','消费已删除':'Expense deleted','放弃当前未保存内容，编辑这笔消费？':'Discard the unsaved draft and edit this expense?','切换周期会清除未保存的表单，继续？':'Switch periods and discard the unsaved draft?','请填写名称及正确的开始、结束日期。':'Enter a name and valid start and end dates.','新周期已创建，所有成员都能看到。':'Period created and visible to everyone.','周期已结束，历史记录已保留。':'Period closed. Past expenses are preserved.',
    '账号尚未加入团队或已停用，请联系管理员。':'Your account is inactive or not a member. Contact your admin.','只有管理员可以操作记账周期。':'Only the admin can manage periods.','该周期尚未开始、已到期或已关闭，不能再修改消费。':'This period is not active. Expenses cannot be changed.','找不到该周期，请重新同步。':'Period not found. Please sync again.','日期与现有未关闭周期重叠，请调整日期。':'These dates overlap another open period.','该周期已建立，请同步后检查。':'This period already exists. Please sync.','普通会员只能记录或修改今天的消费（马来西亚时间）。':'Members can only add or edit today’s expenses (Malaysia time).','消费日期必须在该周期内，且不能晚于今天。':'The date must be within the period and no later than today.','普通会员只能修改自己的消费。':'Members can only edit their own expenses.','该消费已被删除，请取消编辑后检查最新记录。':'This expense was deleted. Cancel editing to see the latest records.','这笔消费已被更新。请取消编辑，重新打开最新记录再修改。':'This expense changed. Cancel editing and reopen the latest entry.','消费资料无效，请检查金额、日期和内容。':'Please check the amount, date and description.','请填写有效周期，结束日期不能早于开始日期，最长 366 天。':'Enter a valid period of up to 366 days.','邮箱或密码不正确，请向管理员确认账号。':'Incorrect email or password. Check with your admin.','账号邮箱尚未确认，请联系管理员。':'This email is unconfirmed. Contact your admin.','云端数据库尚未就绪，请管理员执行数据库初始化脚本。':'The database is not ready. Ask your admin to run the setup script.','操作未完成，请检查网络或登录状态后重试。未确认成功的修改不会显示为已保存。':'Could not confirm the operation. Check your connection and retry.','请先登录并读取团队账本。':'Please sign in and load the ledger first.','正在同步，请稍后再操作。':'Syncing. Please wait a moment.','账号已切换，请检查当前账号。':'The account changed. Please check your current login.','正在保存，请稍后再切换。':'Saving. Please wait before switching.','读取周期失败，请重试。':'Could not load the period. Please retry.','正在保存，请稍后再退出。':'Saving. Please wait before signing out.','新密码至少 12 位，两次输入必须相同。':'Passwords must match and contain at least 12 characters.','密码已修改，下次登录请使用新密码。':'Password updated. Use your new password next time.','修改密码失败。请重新登录后重试，并确认新密码满足项目的密码规则。':'Could not change the password. Sign in again and check the password requirements.',
    '请先执行 upgrade-v3.sql，启用会员与个人资料功能。':'Run upgrade-v3.sql to enable members and profiles.','该邮箱已经有账号，请在会员列表中查找。':'This email already has an account. Check the member list.','无法创建账号，请检查邮箱是否已使用及密码规则。':'Could not create the account. Check the email and password requirements.','密码必须为 12 至 128 位。':'Use a password of 12–128 characters.','只有管理员可以管理会员。':'Only the admin can manage members.','不能修改管理员账号。':'This action cannot change the admin account.','重设密码失败，请重试。':'Could not reset the password. Please retry.','会员账号服务暂不可用，请确认已部署 manage-members，再重试。':'Account service unavailable. Check the manage-members deployment and retry.','管理员尚未连接云端数据库。请按“开通说明”设置项目后再登录。旧个人记录不会自动加入团队账本。':'Cloud setup is incomplete. Follow the setup guide before signing in.','请检查网络及 config.js 中的项目地址和 sb_publishable_ 公开密钥，再刷新页面。':'Check your connection and public settings in config.js, then refresh.',
    '打开账号设置':'Open account settings','关闭账号设置':'Close account settings','关闭记账表单':'Close expense form','主导航':'Main navigation','手机导航':'Mobile navigation','切换明暗模式':'Toggle light and dark mode','记账周期进度':'Period progress','筛选成员':'Filter members','筛选分类':'Filter categories','导出消费记录':'Export expenses','查看记账状态':'View period status'
  };
  const templates=[
    [/^共 (\d+) 笔消费$/,n=>`${n} expenses`],[/^(\d+) 人$/,n=>`${n} people`],[/^(\d+) 笔$/,n=>`${n} entries`],
    [/^(\d+) 位伙伴 · (\d+) 笔日常$/,(a,b)=>`${a} contributors · ${b} expenses`],
    [/^第 (\d+) \/ (\d+) 天$/,(a,b)=>`Day ${a} of ${b}`],[/^共 (\d+) 天（首尾均计入）$/,n=>`${n} days (inclusive)`],
    [/^筛选合计 (.+)$/,n=>`Filtered total ${n}`],[/^(.+) · 马来西亚时间$/,n=>`${n} · Malaysia time`],
    [/^编辑 (.+) 的消费$/,n=>`Edit ${n}’s expense`],[/^删除 (.+) 的「(.+)」？$/,(n,v)=>`Delete “${v}” by ${n}?`],
    [/^结束「(.+)」？所有人将无法再添加、修改或删除本期消费，历史记录仍可查看。$/,n=>`Close “${n}”? No one will be able to change expenses. Past records will be preserved.`],
    [/^(可补记周期内已经过去的日期|会员只可记录当天消费) · (全员可看全部明细|会员只看总额与自己的明细) · 到期后锁定$/,(a,b)=>`${a.startsWith('可')?'Past dates allowed':'Today only'} · ${b.startsWith('全')?'All details visible':'Own details only'} · Locks at end`]
  ];
  let language='zh',theme='light';try{language=localStorage.getItem('family-language')==='en'?'en':'zh';theme=localStorage.getItem('family-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');}catch{}
  const translate=source=>{if(language==='zh')return source;if(en[source])return en[source];for(const [pattern,format] of templates){const match=source.match(pattern);if(match)return format(...match.slice(1));}return source;};
  const originals=new WeakMap(),attributeSources=new WeakMap();
  const excluded='script,style,[data-user-content],.record-title,.record-meta,#period-heading,.signed-in #account-heading,#period-select option,#filter-member option:not(:first-child),.member-name,#account-email';
  function apply(){
    observer.disconnect();document.documentElement.lang=language==='zh'?'zh-CN':'en';document.documentElement.dataset.theme=theme;
    document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#102230':'#dcefff';
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
    while(node=walker.nextNode()){
      if(node.parentElement?.closest(excluded))continue;
      const old=originals.get(node);const source=old&&node.textContent===old.output?old.source:node.textContent;
      const clean=source.trim();const output=clean?source.replace(clean,translate(clean)):source;
      originals.set(node,{source,output});if(node.textContent!==output)node.textContent=output;
    }
    document.querySelectorAll('[placeholder],[aria-label]').forEach(el=>{
      const cache=attributeSources.get(el)||{};
      for(const key of ['placeholder','aria-label']){if(!el.hasAttribute(key))continue;const value=el.getAttribute(key);const source=cache[key]?.output===value?cache[key].source:value;const output=translate(source);cache[key]={source,output};if(value!==output)el.setAttribute(key,output);}
      attributeSources.set(el,cache);
    });
    document.getElementById('language-toggle').textContent=language==='zh'?'EN':'中文';
    document.getElementById('theme-toggle').textContent=theme==='dark'?'☀':'☾';
    document.getElementById('theme-toggle').setAttribute('aria-pressed',String(theme==='dark'));
    observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label']});
  }
  // Give category options stable values before their labels are translated.
  document.querySelectorAll('option:not([value])').forEach(option=>option.value=option.textContent);
  const observer=new MutationObserver(apply);
  document.getElementById('language-toggle').onclick=()=>{language=language==='zh'?'en':'zh';try{localStorage.setItem('family-language',language);}catch{}apply();window.dispatchEvent(new Event('languagechange'));};
  document.getElementById('theme-toggle').onclick=()=>{theme=theme==='dark'?'light':'dark';try{localStorage.setItem('family-theme',theme);}catch{}apply();};
  window.I18n={t:translate,confirm:message=>window.confirm(translate(message)),get language(){return language;}};
  apply();
})();
